retail_insights:
  outputs:
    dev:
      dbname: retail_insights
      host: localhost
      pass: retail_pw
      port: 5433
      schema: staging
      threads: 4
      type: postgres
      user: retail_admin
  target: dev
